#!/usr/bin/python

import time 
import sys
import logging
from ots.worker.api import ResponseClient

LOG = logging.getLogger('')

if __name__ == "__main__":
    
    host, testrun_id = sys.argv[1], sys.argv[2]
    time.sleep(2)

    responseclient = ResponseClient(host, testrun_id)
    responseclient.connect()
    responseclient.set_error("component_test_error", "111")

    
    LOG.error("Error!")
    
    sys.exit(0)
